### ISSUE TITLE
Handle index selection in variable declaration for detection of type of array in expandAllArrays

### ISSUE THREAD

**Issue by QuentinRodier** [UMR-CNRM/pyft#11]
In PHYEX src/common/micro/mode_ice4_sedimentation_split.F90

REAL, DIMENSION(D%NIJT, 0:D%NKT+1) :: ZWSED ! Sedimentation fluxes

The 0: selection is important and is not yet handled by expandAllArrays application

  File "pyft/src/pyft/statements.py", line 61, in aStmtToDoStmt
    upperBound = str(varArray[ind]['as'][i][1])
IndexError: list index out of range

**Comment by SebastienRietteMTO** [comment]
Corrected in 5faa98fa9d3c767cb6e78e0e7bcb9a8e5f1364c5
